version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reciclaedu
    ports: ["5432:5432"]
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/reciclaedu
      - JWT_SECRET=trocasecreta123
      - PORT=4000
    depends_on: [db]
    ports: ["4000:4000"]
  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    environment:
      - REACT_APP_API_URL=http://localhost:4000/api"
volumes:
  db-data: {}
